version: '3'
services:
  # bookie template
  bookie:
    image: apachepulsar/pulsar:3.1.1
    networks:
      - pulsar
    environment:
      - metadataServiceUri=metadata-store:zk:zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181/ledgers
      - BOOKIE_MEM=-Xms64m -Xmx512m -XX:MaxDirectMemorySize=256m
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
      pulsar-init:
        condition: service_completed_successfully
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"