version: '3'
services:
  # zookeeper template
  zookeeper:
    image: zookeeper:3.7.2-jre-17
    networks:
      - pulsar
    environment:
      - ZOO_SERVERS=server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      - ZOO_STANDALONE_ENABLED=false
    # healthcheck无效
    healthcheck:
      # test: nc -z localhost 2181 || exit 1
      test: ["CMD", "curl", "-s", "http://localhost:8080/commands/stat"]
      interval: 10s
      timeout: 5s
      retries: 30
  zoonavigator-temp:
    hostname: zoonavigator
    image: elkozmon/zoonavigator:latest
    networks:
      - pulsar
    environment:
      - HTTP_PORT=9000