
SELECT STATUS FROM V$INSTANCE;
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- 开启所有表和列的变更日志, 通常要先在 CDB$ROOT 容器执行，默认容器可能不是这个，其他容器会继承这个配置，也能覆盖这个配置
-- 查看所有pdb， CDB$ROOT 不包含在其中
SELECT PDB_ID, PDB_NAME, STATUS FROM DBA_PDBS;
-- 当前pdb
SHOW CON_NAME;
ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;


-- 建议开启 FORCE LOGGING（避免直写/批量装载绕过 redo）
ALTER DATABASE FORCE LOGGING;

-- 配置归档日志大小，注意这个参数很重要，超出会被删除，需要确保在这个时间内cdc数据被订阅完，如使用 FRA（快速恢复区），考虑适当增大
ALTER SYSTEM SET db_recovery_file_dest_size = 40G SCOPE=BOTH;
-- SHOW PARAMETER db_recovery_file_dest_size;


CREATE USER C##CDC IDENTIFIED BY "Cdc@123";
-- 查看用户是否Common用户
SELECT USERNAME, COMMON FROM DBA_USERS WHERE USERNAME='C##CDC';

GRANT CREATE SESSION TO C##CDC CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##CDC CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##CDC CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##CDC CONTAINER=ALL;

GRANT LOGMINING TO C##CDC CONTAINER=ALL;