# 启动一个本地kafka集群，本地的host文件要配置kafka主机名指向暴露端口，否则无法连接，因为连接到服务器后返回的各个节点的地址是主机名称如：
# 127.0.0.1 kafka0
# 127.0.0.1 kafka2
# 127.0.0.1 kafka1
version: "3.1" 

services:
  kafka0: &kfk-server
    hostname: kafka0
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "19092:19092"
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # node id + hostname + port
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,CONTROLLER://:9093
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    # volumes: 
    #   - kafka_0_data:/bitnami/kafka
    networks: 
      - kafka-cluster
  kafka1:
    <<: *kfk-server
    hostname: kafka1
    ports:
      - "19093:19093"
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19093,CONTROLLER://:9093
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:19093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    # volumes: 
    #   - kafka_1_data:/bitnami/kafka
    networks: 
      - kafka-cluster
  kafka2:
    <<: *kfk-server
    hostname: kafka2
    ports:
      - "19094:19094"
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19094,CONTROLLER://:9093
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:19094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    # volumes: 
    #   - kafka_2_data:/bitnami/kafka
    networks: 
      - kafka-cluster

networks:
  kafka-cluster: 
    name: kafka-cluster
    ipam:
      driver: default
      config: 
        - subnet: 192.168.164.0/20
# volumes:
#   kafka_0_data:
#     driver: local
#   kafka_1_data:
#     driver: local
#   kafka_2_data:
#     driver: local