version: "3.8" 

services:
  main:
    image: 'docker.io/nginx:1.17.0'
    container_name: main-nginx
    hostname: main-nginx
    ports:
      - 8080:80
      - 8070:70

    # 需要允许共享 ipc 否则 sidecar2 无法启动
    ipc: "shareable"
    networks: 
      - sidecar-cluster

  sidecar1: 
    image: 'docker.io/nginx:1.17.0'
    container_name: sidecar1-nginx
    # 不能配置 hostname 会提示错误 conflicting options: hostname and the network mode
    # hostname: sidecar1-nginx
    # 端口要在主容器暴露
    # ports:
    #   - 8070:70
    volumes:
      - ./conf/default1.conf:/etc/nginx/conf.d/default.conf
      - ./conf/index1.html:/usr/share/nginx/html/index.html
    network_mode: "service:main"

  curl-1: 
    image: 'curlimages/curl'
    container_name: curl-1
    network_mode: "service:main"
    command: ["nc", "-l", "9001"]

  sidecar2: 
    image: 'docker.io/nginx:1.17.0'
    container_name: sidecar2-nginx
    hostname: sidecar2-nginx
    ports:
      - 8060:60
    volumes:
      - ./conf/default2.conf:/etc/nginx/conf.d/default.conf
      - ./conf/index2.html:/usr/share/nginx/html/index.html
    ipc: "service:main"

  curl-2: 
    image: 'curlimages/curl'
    container_name: curl-2
    ipc: "service:main"
    command: ["nc", "-l", "9002"]

  # sidecar3: 
  #   image: 'docker.io/nginx:1.17.0'
  #   container_name: sidecar3-nginx
  #   hostname: sidecar3-nginx
  #   ports:
  #     - 8050:50
  #   volumes:
  #     - ./conf/default3.conf:/etc/nginx/conf.d/default.conf
  #     - ./conf/index3.html:/usr/share/nginx/html/index.html
  #   pid: "service:main"

  # curl-3: 
  #   image: 'curlimages/curl'
  #   container_name: curl-3
  #   pid: "service:main"
  #   command: ["nc", "-l", "9003"]

networks:
  sidecar-cluster: 
    driver: bridge
    name: minio-cluster
