version: '3'
services:
  mysql-server-1:
    hostname: mysql-server-1
    image: mysql/mysql-server:8.0.32
    # ports:
    #   - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ROOT_HOST: "%"
    restart: always
    command: ["mysqld","--server_id=1","--binlog_transaction_dependency_tracking=WRITESET","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
  mysql-server-2:
    hostname: mysql-server-2
    image: mysql/mysql-server:8.0.32
    command: ["mysqld","--server_id=2","--binlog_transaction_dependency_tracking=WRITESET","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    # ports:
    #   - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ROOT_HOST: "%"
    restart: always
  mysql-server-3:
    hostname: mysql-server-3
    image: mysql/mysql-server:8.0.32
    command: ["mysqld","--server_id=3","--binlog_transaction_dependency_tracking=WRITESET","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    # ports:
    #   - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_ROOT_HOST: "%"
    restart: always