version: "3.8" 

x-minio: &minio_tmp
  image: bitnami/minio:2023.12.23
  environment: &minio-env
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
    MINIO_DISTRIBUTED_MODE_ENABLED: yes
    # bitnami镜像 MINIO_VOLUMES 参数不能设置，否则导致脑裂
    # MINIO_VOLUMES: "/bitnami/minio/data-{0...1}"
    # MINIO_DISTRIBUTED_NODES: minio0,minio1,minio2,minio3
    # MINIO_DISTRIBUTED_NODES: minio0/data-0,minio1/data-0,minio2/data-0,minio3/data-0,minio0/data-1,minio1/data-1,minio2/data-1,minio3/data-1
    # 坑爹，只能这样写，逐个节点和磁盘列出不行
    MINIO_DISTRIBUTED_NODES: minio{0...3}/data-{0...1}
    MINIO_SKIP_CLIENT: yes
    MINIO_PROMETHEUS_URL: http://prometheus:9090
    # 这里只配置cluster的jobid
    MINIO_PROMETHEUS_JOB_ID: minio_cluster
    MINIO_PROMETHEUS_AUTH_TYPE: public
  depends_on:
    prepare-data:
      condition: service_completed_successfully
  networks: 
    - minio-cluster
  # healthcheck:
  #   # test: nc -z localhost 2181 || exit 1
  #   test: ["CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
  #   interval: 10s
  #   timeout: 5s
  #   retries: 30
services:
  prepare-data:
    image: 'docker.io/bitnami/os-shell:latest'
    user: root
    # bitnami 镜像指定了用1001:root用户，需要更改，否则挂载的目录是属于root用户的，会导致没权限无法启动
    command:
      - /bin/bash
      - -ec
      - |
        chmod -R g+rwX /data0 /data0-0 /data0-1 /data1 /data1-0 /data1-1 /data2 /data2-0 /data2-1 /data3 /data3-0 /data3-1
    volumes:
      - minio0:/data0
      - minio00:/data0-0
      - minio01:/data0-1
      - minio1:/data1
      - minio10:/data1-0
      - minio11:/data1-1
      - minio2:/data2
      - minio20:/data2-0
      - minio21:/data2-1
      - minio3:/data3
      - minio30:/data3-0
      - minio31:/data3-1

  minio0: 
    << : *minio_tmp
    hostname: minio0
    container_name: minio0
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes: 
      - minio0:/bitnami/minio/data
      - minio00:/data-0
      - minio01:/data-1
  minio1:
    << : *minio_tmp
    hostname: minio1
    container_name: minio1
    volumes: 
      - minio1:/bitnami/minio/data
      - minio10:/data-0
      - minio11:/data-1

  minio2:
    << : *minio_tmp
    hostname: minio2
    container_name: minio2
    volumes: 
      - minio2:/bitnami/minio/data
      - minio20:/data-0
      - minio21:/data-1
  minio3:
    << : *minio_tmp
    hostname: minio3
    container_name: minio3
    volumes: 
      - minio3:/bitnami/minio/data
      - minio30:/data-0
      - minio31:/data-1

  nginx:
    image: nginx:1.25.3
    # hostname: minio-proxy
    ports:
      - "80:80"
    volumes: 
      - ./config/nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    networks: 
      - minio-cluster

  prometheus:
    image: bitnami/prometheus:2.48.1
    hostname: prometheus
    # 默认为1001
    # user: "root"
    container_name: prometheus
    volumes: 
      - prometheus_minio:/opt/bitnami/prometheus/data
      - ./config/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./config/minio-alerting.yml:/opt/bitnami/prometheus/conf/minio-alerting.yml
    ports:
      - 9090:9090
    networks: 
      - minio-cluster

  # grafana:
  #   image: grafana/grafana:10.0.10
  #   hostname: grafana
  #   container_name: grafana
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - grafana_minio:/var/lib/grafana
  #   networks: 
  #     - minio-cluster

networks:
  minio-cluster: 
    driver: bridge
    name: minio-cluster

volumes:
  minio0:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio0'
  minio00:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio00'
  minio01:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio01'

  minio1:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio1'
  minio10:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio10'
  minio11:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio11'
  minio2:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio2'
  minio20:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio20'
  minio21:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio21'
  minio3:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio3'
  minio30:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio30'
  minio31:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data/minio31'

  prometheus_minio:
    driver: local
  # grafana_minio:
  #   driver: local