version: "3.1" 

services:
  kafka0: &kfk-server
    hostname: kafka0
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092"
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # node id + hostname + port
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    # volumes: 
    #   - kafka_0_data:/bitnami/kafka
    networks: 
      - flink-cluster
  kafka1:
    <<: *kfk-server
    hostname: kafka1
    ports:
      - "9092"
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    # volumes: 
    #   - kafka_1_data:/bitnami/kafka
    networks: 
      - flink-cluster
  kafka2:
    <<: *kfk-server
    hostname: kafka2
    ports:
      - "9092"
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    # volumes: 
    #   - kafka_2_data:/bitnami/kafka
    networks: 
      - flink-cluster

  
  jobmanager:
    hostname: jobmanager
    image: flink:1.17.1
    command: jobmanager
    ports:
      - "8081:8081"
    environment: 
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager"
    # volumes: 
    #   - jobmanager_data:/bitnami/kafka
    networks: 
      - flink-cluster
  
  taskmanager:
    hostname: taskmanager
    image: flink:1.17.1
    command: taskmanager
    environment: 
      - "FLINK_PROPERTIES=jobmanager.rpc.address: jobmanager"
    depends_on: 
      - jobmanager
    deploy:
      mode: replicated
      replicas: 3
    # volumes: 
    #   - taskmanager1_data:/bitnami/kafka
    networks: 
      - flink-cluster
  mariadb:
    hostname: mariadb
    image: mariadb/server:10.3
    environment:
      - "MARIADB_ROOT_PASSWORD=mypassword"
    networks: 
      - flink-cluster

networks:
  flink-cluster: 
    name: flink-cluster
    ipam:
      driver: default
      config: 
        - subnet: 192.168.64.0/20
# volumes:
#   kafka_0_data:
#     driver: local
#   kafka_1_data:
#     driver: local
#   kafka_2_data:
#     driver: local