version: "3.1" 

x-flink: &flink
  image: flink:1.20.0-java17
  environment: &flink-env
    FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
  networks: 
    - flink-cluster
x-flink-task: &flink-task
  <<: *flink
  command: taskmanager
  environment: &flink-task-env
    FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
  depends_on: 
    jobmanager:
      condition: service_healthy

services:
  controller0: 
    extends: 
      file: docker-compose-kafka.yml
      service: controller-temp
    container_name: controller0
    hostname: controller0
    environment:
      KAFKA_CFG_NODE_ID: 0
    volumes: 
      - controller_0_data:/bitnami/kafka
  controller1:
    extends: 
      file: docker-compose-kafka.yml
      service: controller-temp
    container_name: controller1
    hostname: controller1
    environment:
      KAFKA_CFG_NODE_ID: 1
    volumes: 
      - controller_1_data:/bitnami/kafka
  controller2:
    extends: 
      file: docker-compose-kafka.yml
      service: controller-temp
    container_name: controller2
    hostname: controller2
    environment:
      KAFKA_CFG_NODE_ID: 2
    volumes: 
      - controller_2_data:/bitnami/kafka
  
  broker0: 
    extends: 
      file: docker-compose-kafka.yml
      service: broker-temp
    container_name: broker0
    hostname: broker0
    environment:
      KAFKA_CFG_NODE_ID: 3
    volumes: 
      - broker_0_data:/bitnami/kafka
  broker1:
    extends: 
      file: docker-compose-kafka.yml
      service: broker-temp
    container_name: broker1
    hostname: broker1
    environment:
      KAFKA_CFG_NODE_ID: 4
    volumes: 
      - broker_1_data:/bitnami/kafka

  jobmanager:
    extends: 
      file: docker-compose-flink.yml
      service: jobmanager-temp
    container_name: jobmgr
    # 因为没有dns, task manager 需要通过 hostname 作为域名访问 jobmanager, 这里需要与 taskmanager 的配置参数 jobmanager.rpc.address 匹配
    hostname: jobmanager
    ports:
      - "8081:8081"
    # volumes: 
    #   - jobmanager_data:/bitnami/kafka
  
  taskmanager0:
    extends: 
      file: docker-compose-flink.yml
      service: taskmanager-temp
    container_name: taskmgr0
    hostname: taskmanager0
    # volumes: 
    #   - taskmanager0_data:/bitnami/kafka
  taskmanager1:
    extends: 
      file: docker-compose-flink.yml
      service: taskmanager-temp
    container_name: taskmgr1
    hostname: taskmanager1
    # volumes: 
    #   - taskmanager1_data:/bitnami/kafka
  sql-gateway:
    extends: 
      file: docker-compose-flink.yml
      service: sql-gateway-temp
    container_name: sql
    hostname: sql-gateway
    ports:
      - "8083:8083"
      
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:11.6.1-rc
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
    # 默认数据目录 /var/lib/mysql
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks: 
      - flink-cluster

networks:
  flink-cluster: 
    name: flink-cluster
    # ipam:
    #   driver: default
    #   config: 
    #     - subnet: 192.168.64.0/20
volumes:
  controller_0_data:
    driver: local
  controller_1_data:
    driver: local
  controller_2_data:
    driver: local
  broker_0_data:
    driver: local
  broker_1_data:
    driver: local
  jobmanager_data:
    driver: local
  taskmanager0_data:
    driver: local
  taskmanager1_data:
    driver: local
  mariadb_data:
    driver: local