version: "3.8" 

services:
  # 这里配子一个容器服务并声明为模板 template
  mysql1: &template
    image: mysql:8.0.33
    restart: always
    hostname: mysql1
    environment:
      - MYSQL_ROOT_PASSWORD=Mypass@112233
      - server_id=1
      - group_replication_local_address=mysql1:33061
    volumes: 
      # 这里挂载绑定无法设定权限，mysql会忽略有写权限的配置文件
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data1:/var/lib/mysql
    # 指定启动命令，但是这里必须以可写方式挂载才能执行，支付方式挂载后再执行就报错了
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && /entrypoint.sh mysqld
      "
    #configs: 
    #  - source: my_config
    #    target: /etc/mysql/conf.d/my.cnf
    #    # 修改为只读权限，否则mysql会忽略, windows上此配置无效，只能用自定义镜像
    #    uid: '999'
    #    gid: '999'
    #    mode: 0440
    networks: 
      - mysql-cluster

  # mysql2:
  #   # 使用前面配置的模板，并覆盖专属的参数
  #   <<: *template
  #   hostname: mysql2
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Mypass@112233
  #     - server_id=2
  #     - group_replication_local_address=mysql2:33061
  #   volumes: 
  #     - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./data2:/var/lib/mysql

  # mysql3:
  #   <<: *template
  #   hostname: mysql3
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Mypass@112233
  #     - server_id=3
  #     - group_replication_local_address=mysql3:33061
  #   volumes: 
  #     - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./data3:/var/lib/mysql
#configs:
#  my_config:
#    file: ./conf/my.cnf
networks:
  mysql-cluster: 
  #  driver: overlay
