version: "3.1" 

services:
  doris-fe1: &fe-server
    image: apache-doris-fe:2.1.2
    hostname: fe1
    # ports:
    #   - 8030:8030
    #   - 9010:9010
    #   - 9020:9020
    #   - 9030:9030
    environment:
      # FE_SERVERS: 1
      FE_ID: 1
      BUILD_TYPE: k8s
      # BROKER_ADDR: INFO,ROLLINGFILE
    # volumes: 
    #   - /tmp/docker/zookeeper/node1/logs:/logs
    #   - /tmp/docker/zookeeper/node1/data:/data
    #   - /tmp/docker/zookeeper/node1/datalog:/datalog
    networks: 
      - doris-net

  # doris-fe2:
  #   <<: *fe-server
  #   hostname: fe2
  #   environment:
  #     ZOO_MY_ID: 2
  #   volumes: 
  #     - /tmp/docker/zookeeper/node2/logs:/logs
  #     - /tmp/docker/zookeeper/node2/data:/data
  #     - /tmp/docker/zookeeper/node2/datalog:/datalog


  doris-be1: &be-server
    image: apache-doris-be:2.1.2
    restart: always
    hostname: be1
    # ports:
    #   - 8040:8040
    #   - 8060:8060
    #   - 9050:9050
    #   - 9060:9060
    environment:
      FE_SERVERS: fe1:fe1:9050
      BE_ADDR: be1:9050
      # NODE_ROLE: computation
      # BROKER_ADDR: INFO,ROLLINGFILE
    # volumes: 
    #   - /tmp/docker/zookeeper/node1/logs:/logs
    #   - /tmp/docker/zookeeper/node1/data:/data
    #   - /tmp/docker/zookeeper/node1/datalog:/datalog
    networks: 
      - doris-net


networks:
  doris-net: 