version: "3.8" 

services:
  doris-fe1: 
    extends: 
      file: docker-compose-base.yml
      service: doris-fe1

  doris-fe2:  
    extends: 
      file: docker-compose-base.yml
      service: doris-fe2

  doris-fe3:  
    extends: 
      file: docker-compose-base.yml
      service: doris-fe3

  doris-be1: 
    extends: 
      file: docker-compose-base.yml
      service: doris-be1

  doris-be2: 
    extends: 
      file: docker-compose-base.yml
      service: doris-be2

  doris-be3: 
    extends: 
      file: docker-compose-base.yml
      service: doris-be3

networks:
  default: 
    name: doris-net