# version: "3.8"
services:

  web-usernon:
    # 镜像在 dockerfile 中没有指定用户
    build: img/usernon
    pull_policy: build
    image: 'user-non:0.0.1'
    # entrypoint: 
    #   - /data/user-info.sh
    environment:
      - ENV_FILE=usernon
    container_name: usernon
    volumes: 
      - localdir:/data
      - volume1:/data2

  web-userid:
    # 镜像在 dockerfile 中指定了用户名 USER 1001
    build: img/userid
    pull_policy: build
    image: 'user-id:0.0.1'
    # 因为 dockerfile 指定 USER 1001, 所以没有默认用户名, 也没有用户目录, 用户就是其id， 也可以指定其他用户
    # entrypoint:  
    #   - /data/user-info.sh
    container_name: userid
    environment:
      - ENV_FILE=userid
    volumes: 
      - localdir:/data
      - volume1:/data2

  web-username:
    # 镜像在 dockerfile 中指定了用户名 USER testuser
    build: img/username
    pull_policy: build
    image: 'user-name:0.0.1'
    
    # 默认为 dockerfile 中 user 指定的用户名,不能指定 /etc/passwd 中没有的用户名
    user: testuser
    # entrypoint:  
    #   - /data/user-info.sh
    container_name: username
    environment:
      - ENV_FILE=username
    volumes: 
      - localdir:/data
      - volume1:/data2

volumes:
  localdir:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './data'
  volume1: