x-fe: &fe
  image: "apache/doris:2.0.0_alpha-fe-x86_64"
  entrypoint: 
    - bash
    - -x
    - /opt/apache-doris/fe/bin/start_fe.sh
  healthcheck:
    test: ["CMD", "/opt/apache-doris/healthcheck.sh", "9030"]
    interval: 2s
    timeout: 60s
    retries: 20

x-be: &be
  image: "apache/doris:2.0.0_alpha-be-x86_64"
  entrypoint: 
    - bash
    - -x
    - /opt/apache-doris/be/bin/start_be.sh
  healthcheck:
    test: ["CMD", "ls", "/opt/apache-doris/be/bin/be.pid"]
    interval: 2s
    timeout: 60s
    retries: 20
  depends_on:
    docker-fe-01: 
      condition: service_healthy

version: '3'
services:
  docker-fe-01: 
    << : *fe
    container_name: "fe01"
    hostname: "fe01"
    volumes:
      - ./data/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-01/log:/opt/apache-doris/fe/log
      - ./conf/fe.conf:/opt/apache-doris/fe/conf/fe.conf:ro
      - ./conf/healthcheck.sh:/opt/apache-doris/healthcheck.sh
    networks:
      doris_net:

  docker-fe-02: 
    << : *fe
    container_name: "fe02"
    hostname: "fe02"
    command: 
      - --helper
      - fe01:9010
    volumes:
      - ./data/fe-02/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-02/log:/opt/apache-doris/fe/log
      - ./conf/fe.conf:/opt/apache-doris/fe/conf/fe.conf:ro
      - ./conf/healthcheck.sh:/opt/apache-doris/healthcheck.sh
    networks:
      doris_net:
    healthcheck:
      test: ["CMD", "ls", "/opt/apache-doris/fe/bin/fe.pid"]
      interval: 2s
      timeout: 60s
      retries: 20
    depends_on:
      docker-fe-01: 
        condition: service_healthy

  docker-fe-03: 
    << : *fe
    container_name: "fe03"
    hostname: "fe03"
    command: 
      - --helper
      - fe01:9010
    volumes:
      - ./data/fe-03/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-03/log:/opt/apache-doris/fe/log
      - ./conf/fe.conf:/opt/apache-doris/fe/conf/fe.conf:ro
      - ./conf/healthcheck.sh:/opt/apache-doris/healthcheck.sh
    networks:
      doris_net:
    healthcheck:
      test: ["CMD", "ls", "/opt/apache-doris/fe/bin/fe.pid"]
      interval: 2s
      timeout: 60s
      retries: 20
    depends_on:
      docker-fe-01: 
        condition: service_healthy

  docker-be-01:
    << : *be
    container_name: "be01"
    hostname: "be01"
    environment:
      BE_ADDR: be01:9050
    volumes:
      - ./data/be-01/storage:/opt/apache-doris/be/storage
      - ./data/be-01/script:/docker-entrypoint-initdb.d
      - ./data/be-01/log:/opt/apache-doris/be/log
    networks:
      doris_net:
  docker-be-02:
    << : *be
    container_name: "be02"
    hostname: "be02"
    environment:
      BE_ADDR: be02:9050
    volumes:
      - ./data/be-02/storage:/opt/apache-doris/be/storage
      - ./data/be-02/script:/docker-entrypoint-initdb.d
      - ./data/be-02/log:/opt/apache-doris/be/log
    networks:
      doris_net:
  docker-be-03:
    << : *be
    container_name: "be03"
    hostname: "be03"
    environment:
      BE_ADDR: be03:9050
    volumes:
      - ./data/be-03/storage:/opt/apache-doris/be/storage
      - ./data/be-03/script:/docker-entrypoint-initdb.d
      - ./data/be-03/log:/opt/apache-doris/be/log
    networks:
      doris_net:


  init-c:
    image: mysql:8.4.0
    container_name: "init"
    entrypoint:
      - bash
      - -x
      - /opt/apache-doris/init/init.sh
    volumes: 
      - ./conf/init/init.sh:/opt/apache-doris/init/init.sh
    depends_on:
      docker-fe-02:
        condition: service_healthy
      docker-fe-03:
        condition: service_healthy
      docker-be-01:
        condition: service_healthy
      docker-be-02:
        condition: service_healthy
      docker-be-03:
        condition: service_healthy
    networks:
      doris_net:

networks:
  doris_net:
